### ISSUE TITLE
RangeError: source is too large

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/xsalsa20#1]
![image](https://user-images.githubusercontent.com/1270099/31780213-aae03334-b4ba-11e7-93a3-06316b1ac2b8.png)

We've gotten this in Beaker for one user. It happened first, afaik, when she tried to write an image to a dat. Now it seems to happen when she loads another specific dat.

**Comment by taskinosman** [comment]
Hi, we have launched an electron project which also has xsalsa20 dependency. I am sending the logs from clients to sentry. Users keep getting uncaught exception like the screenshot above. Full Stacktrace follows. Node 7.9 inside electron.  I have 3 reports from users with exactly same stack as follows:

```
RangeError: Source is too large
  ?, in Uint8Array.set
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/xsalsa20/index.js", line 46, col 19, in new WASM
    xsalsa20.memory.set(key, this._key)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/xsalsa20/index.js", line 17, col 46, in new XSalsa20
    this._xor = xsalsa20 && xsalsa20.exports ? new WASM(nonce, key) : new Fallback(nonce, key)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/xsalsa20/index.js", line 14, col 43, in XSalsa20
    if (!(this instanceof XSalsa20)) return new XSalsa20(nonce, key)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/sodium-javascript/crypto_stream.js", line 23, col 20, in new XOR
    this._instance = xsalsa20(nonce, key)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/sodium-javascript/crypto_stream.js", line 19, col 10, in Object.exports.crypto_stream_xor_instance
    return new XOR(nonce, key)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js", line 283, col 32, in Protocol._onopen
    this._remoteXor = sodium.crypto_stream_xor_instance(this._remoteNonce, this.key)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js", line 311, col 17, in Protocol._onmessage
    return this._onopen(id, data, start, end)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js", line 365, col 10, in Protocol._parseMessage
    this._onmessage(data, start, end)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js", line 330, col 37, in Protocol._parse
    if (this._missing) start = this._parseMessage(data, start)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js", line 238, col 8, in Protocol._write
    this._parse(data, 0, cb)
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js", line 406, col 64, in doWrite
    if (writev) stream._writev(chunk, state.onwrite);else stream._write(chunk, encoding, state.onwrite);
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js", line 395, col 5, in writeOrBuffer
    doWrite(stream, state, false, len, chunk, encoding, cb);
  File "/Applications/SetupVPN.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js", line 322, col 11, in Protocol.Writable.write
    ret = writeOrBuffer(this, state, isBuf, chunk, encoding, cb);
  File "_stream_readable.js", line 557, col 20, in Socket.ondata
  File "events.js", line 96, col 13, in emitOne
  File "events.js", line 191, col 7, in Socket.emit
  File "_stream_readable.js", line 178, col 18, in readableAddChunk
  File "_stream_readable.js", line 136, col 10, in Socket.Readable.push
  File "net.js", line 560, col 20, in TCP.onread
```

**Comment by taskinosman** [comment]
![image](https://user-images.githubusercontent.com/22910022/34386089-f0be0a50-eaf4-11e7-8af4-5643c53a482e.png)

**Comment by pfrazee** [comment]
@taskinosman what version of xsalsa20 is your package using?

**Comment by pfrazee** [comment]
This is still being reported in Beaker. See https://github.com/beakerbrowser/beaker/issues/760#issuecomment-377694871

**Comment by AHFriedman** [comment]
I'm also seeing a similar error (if not the same) on xsalsa20@1.1.0.

I'm not sure if this belongs on this thread, or if its the fault of another package, but this is the stacktrace: 

`\node_modules\xsalsa20\index.js:49
xsalsa20.memory.set(key, this._key)
                   ^
RangeError: Source is too large
     at Uint8Array.set (<anonymous>)
     at new WASM (node_modules\xsalsa20\index.js:49:19)
     at new XSalsa20 (node_modules\xsalsa20\index.js:20:46)
     at XSalsa20 (node_modules\xsalsa20\index.js:17:43)
     at Object.module.exports.createBoxStream (node_modules\libp2p-pnet\src\crypto.js:21:15)
     at Timeout._onTimeout (node_modules\libp2p-pnet\src\state.js:94:23)
     at listOnTimeout (internal/timers.js:531:17)
     at processTimers (internal/timers.js:475:7)
`
The odd thing is that, its able to run for some time before this problem occurs....
